[package]
name = "blame"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
crossterm = "0.27.0"
ratatui = "0.27.0"
regex = "1.10.2"
syntect = "5.2.0"
ansi-to-tui = "5.0.0-rc.1"
